= Build a custom Collector for Explorer
:toc: right
:enonicStart: https://developer.enonic.com/start
:enonicTasks: https://developer.enonic.com/docs/xp/stable/framework/tasks

This guide takes you through the steps of building a custom Collector for Explorer.

== Introduction

Collectors are implemented as standard XP applications. They essentially consist of two main components:

Form:: A React based user interface that enable search administrators to instruct the collector in it’s specific activities.

Task:: Code that performs the actual retrieval of content for indexing.

This section will guide you through the basic steps of building your own custom collector.

== Create project

To set up a project locally, run the following command and complete the steps:

  enonic project create -r starter-lib

NOTE: *Don't have Enonic CLI?* Visit the {enonicStart}[Getting started guide] to install it.

== Building the application

From the project folder created (i.e. `myproject/`), run this command:

  enonic project build

This command produces a .jar file in the folder `build/libs/` i.e. `build/libs/myproject.jar`

== Deploying the application to a sandbox

From the project folder created (i.e. `myproject/`), run this command:

  enonic project deploy

This command copies the .jar file from the `build/libs/` folder into the sandbox home deploy folder.

== Development

=== Including the Explorer Library

This should already be set up in the starter.

.build.gradle
[source,gradle]
----
dependencies {
    include 'com.enonic.lib:lib-explorer:4.0.0'
}
----

=== Configure collectors.json

You can include multiple collectors in a single enonic xp application.
If you only include one, the collectors.json file should still contain an array with a single object entry.

Each collector needs to have it's own unique library name so React can access it on the window object.

The library name must match up between webpack.config.babel.js and src/main/resources/collectors.json

.webpack.config.babel.js
[source,java]
----
const config = {
    entry: {
        'MyCollectorNameA': './CollectorA.jsx',
        'MyCollectorNameB': './CollectorB.jsx',
    },
    output: {
        filename: '[name].esm.js',
        library: 'Lib[name]',
        libraryTarget: 'var',
    }
}
----

./src/main/resources/collectors.json
[source,json]
----
[{
    "componentPath": "window.LibMyCollectorNameA.Collector",
    "configAssetPath": "react/MyCollectorNameA.esm.js",
    "displayName": "My collector A",
    "taskName": "collectA"
},{
    "componentPath": "window.LibMyCollectorNameB.Collector",
    "configAssetPath": "react/MyCollectorNameB.esm.js",
    "displayName": "My collector B",
    "taskName": "collectB"
}]
----

=== Configure documentTypes.json

You can include multiple document-types in a single enonic xp application.
If you only include one, the documentTypes.json file should still contain an array with a single object entry.

Each document-type must have a unique _name property.

Those document-type names can then be used when persisting documents in you collector task code.

./src/main/resources/documentTypes.json
[source,json]
----
[{
    "_name": "starter_explorer_collector_document_type_a",
    "addFields": false,
    "properties": [{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "text",
        "nGram": true,
        "path": false,
        "valueType": "string"
    },{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "title",
        "nGram": true,
        "path": false,
        "valueType": "string"
    },{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": false,
        "max": 0,
        "min": 1,
        "name": "url",
        "nGram": false,
        "path": false,
        "valueType": "string"
    }]
},{
    "_name": "starter_explorer_collector_document_type_b",
    "addFields": false,
    "properties": [{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "propertyName",
        "nGram": true,
        "path": false,
        "valueType": "string"
    }]
}]
----

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
collector.persistDocument(documentToPersist, {
    documentTypeName: 'starter_explorer_collector_document_type'
});
----

=== Developing the Task

An example is provided in the starter.

It uses the normal {enonicTasks}[task framework], but has some useful extensions.

The task recives the following properties, when called from the Explorer Admin GUI Application:
* collectionId
* collectorId
* configJson
* language

The task descriptor xml must declare these properties:

./src/main/resources/tasks/collect/collect.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<task>
	<description>Collect</description>
	<form>
		<input name="collectionId" type="TextLine">
			<label>Collection ID</label>
			<occurrences minimum="0" maximum="1"/>
		</input>
		<input name="collectorId" type="TextLine">
			<label>Collector ID</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="configJson" type="TextLine">
			<label>Config JSON</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="language" type="TextLine">
			<label>Language</label>
			<occurrences minimum="0" maximum="1"/>
		</input>
	</form>
</task>
----

The task controller typescript file can then pass these properties via the Collector class constructor:

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
import {Collector} from '/lib/explorer';

export function run({
    collectionId,
    collectorId,
    configJson,
    language
}) {
    const collector = new Collector<CollectorConfig>({
        collectionId, collectorId, configJson, language
    });
}
----
